### ISSUE TITLE
The page bounces up and down while I'm typing

### ISSUE THREAD

**Issue by DeterminantX** [davidrusu/type-the-web#30]
Start typing the second paragrapth ("What do I intend to...") from:

belliottsmith.com/eventual-consistency-concurrent-data-structures/

and notice how the page jumps up and down with each typed character

**Comment by davidrusu** [comment]
That sounds very weird, I can't replicate it on my end. What version of firefox are you using?

**Comment by DeterminantX** [comment]
Latest and greatest(?).

I tried again and noticed that it only happens when I'm zoomed in (the font was somewhat smallish on that page)
