### ISSUE TITLE
Words get squished together

### ISSUE THREAD

**Issue by DeterminantX** [davidrusu/type-the-web#31]
I noticed that words get squished together and it looks like this is when a chunk starts or ends with a space (the space disappears).

Examples:
Type some code snippet from the first answer:
http://stackoverflow.com/questions/27772356/the-concept-of-currying

Type the second sentence in the second paragraph ("I love teasing... by matching its constraints.."):
http://belliottsmith.com/eventual-consistency-concurrent-data-structures/

I think the spaces should only be removed if they are redundant (eg. if a block ends in a space and the next block starts with a space).

**Comment by davidrusu** [comment]
fixed in 1.2
