### ISSUE TITLE
The automatic scrolling should scroll a little higher

### ISSUE THREAD

**Issue by DeterminantX** [davidrusu/type-the-web#32]
The automatic scrolling is nice but it places the text a little too low (it looks like it's about 40% down from the top of the screen).

Can you please move it closer to the top so that it feels more natural? (perhaps about 20% to 25% down from the top of the screen).

For reference, I'm looking at the following:
http://aeon.co/magazine/psychology/why-do-doctors-deny-death-to-the-terminally-ill/

**Comment by davidrusu** [comment]
fixed in 1.2
