### ISSUE TITLE
Weird layout & spacing changes as you type

### ISSUE THREAD

**Issue by DeterminantX** [davidrusu/type-the-web#38]
Something weird happens when you try to type the first or second paragraph.  Words get jammed into each other and the rest of the block continues on a new line:

https://www.packet.net/blog/how-we-failed-at-openstack

**Comment by davidrusu** [comment]
I implemented a fix that works for this site, but I feel like it might
break some other changes, I'll use it for a few days and see If I notice
any regressions before pushing a new version.
