### ISSUE TITLE
WPM #s are cut off from the chart

### ISSUE THREAD

**Issue by DeterminantX** [davidrusu/type-the-web#40]
I'm typing the following page and the WPM numbers are cut off from the graph:

http://www.bailis.org/blog/worst-case-distributed-systems-design/

The side panel has a horizontal scroll bar so it only shows part of the graph leading to the numbers being cut off.  Can the numbers be displayed on the left side instead of the right?  Not sure if this is related but I had the page zoomed in a bit before starting the add-on.

**Comment by DeterminantX** [comment]
I just updated the add-on at work and tried it for the very second time (so I definitely didn't resize it the side bar at work) and I can only see part of the words per minute.  At first it looked like it was just barely fine but then I jammed a bunch of keys to get past 100 wpm and then I could only see the first digit going forward once I went back to regular typing.

Perhaps increasing the default size of that sidebar or reducing the spacing around the chart might do the trick since only a bit more space for 2 more characters is needed

**Comment by davidrusu** [comment]
Resizing the side bar is not possible by the addon-sdk

**Comment by davidrusu** [comment]
I made the chart smaller by 5px, hopefully it fixes the problem for you
