### ISSUE TITLE
I don't know where the cursor is and where tab would take me

### ISSUE THREAD

**Issue by DeterminantX** [davidrusu/type-the-web#41]
I'm trying to type:

http://www.csd.uwo.ca/~magi/personal/humour/Computer_Audience/The%20Parable%20of%20the%20Two%20Programmers.html

but once I select where I want to start typing, I'm lost so I'm not quite sure what character I need to start with.  This is especially troublesome when blocks start with whitespace.

I would like see some indication of what the current block is so I can see where it starts and also so I can see where it ends so that I know where tab would take me.  

The previous version had orange highlighting so something similar would be nice.

**Comment by davidrusu** [comment]
I've added some highlighting around text when first entering a text node that diseapears once you start typing
