### ISSUE TITLE
Chart rolls over too quickly

### ISSUE THREAD

**Issue by DeterminantX** [davidrusu/type-the-web#42]
The chart currently rolls over much too quickly.  The 1 minute timeframe should be atleast 5 minutes.

If the width of the chart is a concern, it should be possible to maintain the same # of points plotted by the chart and just increase the coverage so that each point spans a longer amount of time (and perhaps update the current WPM calculation to use the longer timeframe).

A slower moving chart should also reduce the amount of moving distraction while typing.

**Comment by davidrusu** [comment]
Modifying the charting library is diffucult as Mozilla won't allow direct modifications. 

The problem with slow moving charts is that the data becomes very squished. This is what it looks like with 5 minutes, would you be happy with this:
![chart_5min](https://cloud.githubusercontent.com/assets/1832378/6131015/2f8ce0aa-b117-11e4-9aa9-4fbff53c980a.png)

**Comment by DeterminantX** [comment]
Yeah that looks fine.  If you want to reduce the number of points then you could perhaps only update the current WPM every other key stroke (or mod n etc.)

**Comment by davidrusu** [comment]
fixed in 1.7
