### ISSUE TITLE
Include more dividers in the chart

### ISSUE THREAD

**Issue by DeterminantX** [davidrusu/type-the-web#45]
The chart currently has 2 dividers (a third of top speed and 2 thirds of the top speed).

Practically all of my time is spent in the top third so those additional guide lines don't help because they are too far apart.  This becomes more of a problem the faster you type (imagine typing at 150 WPM, the second guide line would only help when you slow down by 50 WPM).

Instead of dividing the chart in 3, would it be possible to divide it in 4?

**Comment by DeterminantX** [comment]
In addition to the extra guide line, It would probably look better to include a guide line at 0 and the top speed as well.

**Comment by davidrusu** [comment]
I agree, I changed it to have 3 lines ( that commit message is wrong), 4 lines messes with the spacing a bit. I also added the border around the chart
