### ISSUE TITLE
Cannot type angled-opening-quote character correctly

### ISSUE THREAD

**Issue by DeterminantX** [davidrusu/type-the-web#46]
In the last large paragraph (the one starting with "All this and more") has 'Your Computer' with angled single quotes.  I'm not able to type the opening single quote correctly.

http://thad.frogley.info/archive/the_greatest_program.html

**Comment by davidrusu** [comment]
The first quote is actually a back-tick. It's the key above your tab. This char is used in haskell for calling functions as postfix operators so I don't think it should be mapped to something more common

**Comment by DeterminantX** [comment]
I see.  Agreed. Closing issue
